# Shell variables
# Generated by 'wal'
wallpaper='/home/inazurai/Downloads/retro.jpg'

# Special
background='#0B0716'
foreground='#f1efdf'
cursor='#f1efdf'

# Colors
color0='#0B0716'
color1='#CE9977'
color2='#D86B8F'
color3='#AFA591'
color4='#D5AD97'
color5='#DDD2AF'
color6='#E2DAC9'
color7='#f1efdf'
color8='#a8a79c'
color9='#CE9977'
color10='#D86B8F'
color11='#AFA591'
color12='#D5AD97'
color13='#DDD2AF'
color14='#E2DAC9'
color15='#f1efdf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
