#! /bin/sh

~/.config/polybar/launch.sh

# Start compton
compton -b --config ~/.config/compton/compton.conf
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a alacritty desktop ='^1' follow=on focus=on
bspc rule -a Thunar desktop ='^2' follow=on focus=on
bspc rule -a firefox desktop ='^3' follow=on focus=on
bspc rule -a chromium desktop ='^4' follow=on focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

bspc config presel_feedback_color "$color1"

bspc config focus_follows_pointer true

